import { Route, VehicleType, TravelStatus, TouristSpot } from "./types";

export const ROUTES: Route[] = [
  {
    id: "r1",
    from: "Dimapur",
    to: "Kohima",
    vehicleType: VehicleType.SUMO,
    departureDate: "12 May 2024",
    departureTime: "06:30 AM",
    arrivalTime: "09:30 AM",
    price: 350,
    availableSeats: 4,
    totalSeats: 10,
    status: TravelStatus.ON_TIME,
    safetyRating: 4.8,
    tags: ["Express", "Frequent"],
  },
  {
    id: "r2",
    from: "Kohima",
    to: "Dimapur",
    vehicleType: VehicleType.BUS,
    departureDate: "12 May 2024",
    departureTime: "07:00 AM",
    arrivalTime: "10:30 AM",
    price: 150,
    availableSeats: 12,
    totalSeats: 32,
    status: TravelStatus.DELAYED,
    safetyRating: 4.5,
    tags: ["Budget", "Morning"],
  },
  {
    id: "r3",
    from: "Kohima",
    to: "Mokokchung",
    vehicleType: VehicleType.SUMO,
    departureDate: "12 May 2024",
    departureTime: "05:30 AM",
    arrivalTime: "12:30 PM",
    price: 700,
    availableSeats: 2,
    totalSeats: 10,
    status: TravelStatus.ON_TIME,
    safetyRating: 4.6,
    tags: ["Mountain Road", "Scenic"],
  },
  {
    id: "r4",
    from: "Mokokchung",
    to: "Kohima",
    vehicleType: VehicleType.SUMO,
    departureDate: "12 May 2024",
    departureTime: "06:00 AM",
    arrivalTime: "01:00 PM",
    price: 700,
    availableSeats: 6,
    totalSeats: 10,
    status: TravelStatus.ON_TIME,
    safetyRating: 4.6,
    tags: ["Direct"],
  },
  {
    id: "r5",
    from: "Kohima",
    to: "Tuensang",
    vehicleType: VehicleType.SUMO,
    departureDate: "13 May 2024",
    departureTime: "05:00 AM",
    arrivalTime: "04:00 PM",
    price: 1200,
    availableSeats: 1,
    totalSeats: 10,
    status: TravelStatus.ON_TIME,
    safetyRating: 4.4,
    tags: ["Long Distance", "Rugged"],
  },
  {
    id: "r6",
    from: "Dimapur",
    to: "Wokha",
    vehicleType: VehicleType.SUMO,
    departureDate: "13 May 2024",
    departureTime: "08:00 AM",
    arrivalTime: "12:00 PM",
    price: 450,
    availableSeats: 8,
    totalSeats: 10,
    status: TravelStatus.ON_TIME,
    safetyRating: 4.7,
    tags: ["Comfort"],
  },
];

export const TOURIST_SPOTS: TouristSpot[] = [
  {
    id: "t1",
    name: "Dzukou Valley",
    description: "A breathtaking valley known for its rolling green hills and rare Dzukou lily.",
    location: "Kohima / Manipur Border",
    bestTime: "June - September (Lillies), Oct - May (Lush green)",
    travelTip: "Start your trek from Viswema for an easier ascent.",
    safetyNote: "Temperatures can drop below zero in winter. Carry warm clothes.",
    category: "Nature",
  },
  {
    id: "t2",
    name: "Khonoma Village",
    description: "Asia's first green village, famous for its conservation efforts and history.",
    location: "Kohima District",
    bestTime: "All year round",
    travelTip: "Book a local guide to learn about Angami culture and history.",
    safetyNote: "Respect local customs; avoid loud noise in residential areas.",
    category: "Culture",
  },
  {
    id: "t3",
    name: "Triple Falls",
    description: "A stunning three-tier waterfall located in Seithekima village.",
    location: "Dimapur",
    bestTime: "Monsoon (Peak flow)",
    travelTip: "Great for hiking and photography.",
    safetyNote: "Rocks can be slippery during rains. Wear sturdy shoes.",
    category: "Nature",
  },
  {
    id: "t4",
    name: "Hornbill Festival (Kisama)",
    description: "The 'Festival of Festivals' showcasing the rich culture of Nagaland's tribes.",
    location: "Nagaland Heritage Village, Kohima",
    bestTime: "December 1st - 10th",
    travelTip: "Book accommodation months in advance.",
    safetyNote: "Very crowded; keep your belongings secure.",
    category: "Culture",
  },
  {
    id: "t5",
    name: "Japfu Peak",
    description: "The second highest peak in Nagaland, offering panoramic views of the hills.",
    location: "Kohima",
    bestTime: "November - March",
    travelTip: "Famous for the tallest rhododendron tree.",
    safetyNote: "Trekking requires good stamina and a local guide.",
    category: "Adventure",
  },
];

export const LOCATIONS = [
  "Dimapur",
  "Kohima",
  "Mokokchung",
  "Tuensang",
  "Wokha",
  "Phek",
  "Zunheboto",
  "Mon",
  "Peren",
  "Kiphire",
  "Longleng",
  "Noklak",
  "Shamator",
  "Tseminyu",
  "Niuland",
  "Chümoukedima",
];
